// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using topfact.Pulse.Data;

#nullable disable

namespace topfact.Pulse.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260902124315_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("topfact.Pulse.Models.PulseAccess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BereichID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("GruppeID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("View");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("GruppeID");

                    b.HasIndex("BereichID", "GruppeID");

                    b.HasIndex("Username", "IsActive");

                    b.ToTable("Pulse_Access", "dbo");
                });

            modelBuilder.Entity("topfact.Pulse.Models.PulseBereich", b =>
                {
                    b.Property<int>("BereichID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BereichID"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RequiredRole")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("BereichID");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.ToTable("Pulse_Bereich", "dbo");
                });

            modelBuilder.Entity("topfact.Pulse.Models.PulseConnector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiConfig")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("api_config");

                    b.Property<string>("Bezeichnung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConnectorType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("connector_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int?>("KategorieID")
                        .HasColumnType("int");

                    b.Property<string>("ManualConfig")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("manual_config");

                    b.Property<string>("SqlConfig")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sql_config");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.ToTable("Pulse_ConnectorManager", "dbo");
                });

            modelBuilder.Entity("topfact.Pulse.Models.PulseGruppe", b =>
                {
                    b.Property<int>("GruppeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GruppeID"));

                    b.Property<int>("BereichID")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCollapsible")
                        .HasColumnType("bit");

                    b.Property<bool>("IsExpandedDefault")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("GruppeID");

                    b.HasIndex("IsActive");

                    b.HasIndex("BereichID", "Code")
                        .IsUnique();

                    b.ToTable("Pulse_Gruppe", "dbo");
                });

            modelBuilder.Entity("topfact.Pulse.Models.PulseKategorie", b =>
                {
                    b.Property<int>("KategorieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KategorieID"));

                    b.Property<string>("BadgeText")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int?>("ConnectorID")
                        .HasColumnType("int");

                    b.Property<int>("GruppeID")
                        .HasColumnType("int");

                    b.Property<string>("IconCss")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RouteBereich")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Sql_query")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("KategorieID");

                    b.HasIndex("IsActive");

                    b.HasIndex("GruppeID", "Title")
                        .IsUnique();

                    b.ToTable("Pulse_Kategorie", "dbo");
                });

            modelBuilder.Entity("topfact.Pulse.Models.PulseKpiDefinition", b =>
                {
                    b.Property<int>("KpiDefinitionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("KpiDefinitionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KpiDefinitionID"));

                    b.Property<string>("Bereich")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("#338562");

                    b.Property<int?>("ConnectorID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DisplayStyle")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IconCss")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasDefaultValue("ri-bar-chart-line");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("KategorieID")
                        .HasColumnType("int");

                    b.Property<string>("QuerySql")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<double?>("TargetValue")
                        .HasColumnType("float");

                    b.Property<double?>("ThresholdGreen")
                        .HasColumnType("float");

                    b.Property<double?>("ThresholdYellow")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<double?>("ToleranceAbsolute")
                        .HasColumnType("float");

                    b.Property<double?>("TolerancePercent")
                        .HasColumnType("float");

                    b.Property<string>("Unit")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("KpiDefinitionID");

                    b.HasIndex("Bereich");

                    b.HasIndex("IsActive");

                    b.HasIndex("KategorieID");

                    b.ToTable("Pulse_KpiDefinition", "dbo");
                });

            modelBuilder.Entity("topfact.Pulse.Models.PulseLogin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ip_address");

                    b.Property<DateTime>("LoginTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("login_time");

                    b.Property<bool>("Success")
                        .HasColumnType("bit")
                        .HasColumnName("success");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("Success");

                    b.HasIndex("Username", "LoginTime");

                    b.ToTable("Pulse_Logins", "dbo");
                });

            modelBuilder.Entity("topfact.Pulse.Models.PulseQueryResult", b =>
                {
                    b.Property<int>("QueryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QueryID"));

                    b.Property<string>("Daten")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KategorieID")
                        .HasColumnType("int");

                    b.Property<string>("Sql_query")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.HasKey("QueryID");

                    b.HasIndex("KategorieID");

                    b.ToTable("Pulse_QueryResults", "dbo");
                });

            modelBuilder.Entity("topfact.Pulse.Models.PulseAccess", b =>
                {
                    b.HasOne("topfact.Pulse.Models.PulseBereich", "Bereich")
                        .WithMany("Accesses")
                        .HasForeignKey("BereichID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("topfact.Pulse.Models.PulseGruppe", "Gruppe")
                        .WithMany("Accesses")
                        .HasForeignKey("GruppeID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Bereich");

                    b.Navigation("Gruppe");
                });

            modelBuilder.Entity("topfact.Pulse.Models.PulseGruppe", b =>
                {
                    b.HasOne("topfact.Pulse.Models.PulseBereich", "Bereich")
                        .WithMany("Gruppen")
                        .HasForeignKey("BereichID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bereich");
                });

            modelBuilder.Entity("topfact.Pulse.Models.PulseKategorie", b =>
                {
                    b.HasOne("topfact.Pulse.Models.PulseGruppe", "Gruppe")
                        .WithMany("Kategorien")
                        .HasForeignKey("GruppeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gruppe");
                });

            modelBuilder.Entity("topfact.Pulse.Models.PulseKpiDefinition", b =>
                {
                    b.HasOne("topfact.Pulse.Models.PulseKategorie", "Kategorie")
                        .WithMany()
                        .HasForeignKey("KategorieID");

                    b.Navigation("Kategorie");
                });

            modelBuilder.Entity("topfact.Pulse.Models.PulseQueryResult", b =>
                {
                    b.HasOne("topfact.Pulse.Models.PulseKategorie", "Kategorie")
                        .WithMany()
                        .HasForeignKey("KategorieID");

                    b.Navigation("Kategorie");
                });

            modelBuilder.Entity("topfact.Pulse.Models.PulseBereich", b =>
                {
                    b.Navigation("Accesses");

                    b.Navigation("Gruppen");
                });

            modelBuilder.Entity("topfact.Pulse.Models.PulseGruppe", b =>
                {
                    b.Navigation("Accesses");

                    b.Navigation("Kategorien");
                });
#pragma warning restore 612, 618
        }
    }
}
